### ISSUE TITLE
Chapter1: tomcat 不能连接 mysql

### ISSUE THREAD

**Issue by thelark** [kubeguide/samplecode#1]

**Comment by pinggit** [comment]
我碰到了一样的问题。原因是mysql版本更新了。
书里的例子是在mysql5.7 下的。

我mysql-rc.yaml改了一行解决了
这行：
```
image: mysql
```
改成：
```
image: mysql:5.7
```

我用的mysql-rc.yaml文件：
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_SERVICE_HOST
          value: 'mysql'
        - name: MYSQL_SERVICE_PORT
          value: '3306'
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
```
