### ISSUE TITLE
第三章的示例代码没有发布吗？

### ISSUE THREAD

**Issue by pinggit** [kubeguide/samplecode#2]
比如3.7.5 这个例子

```yaml
$ cat samplecode-my/frontend-controller.yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend
  labels:
    name: frontend
spec:
  replicas: 1
  selector:
    name: frontend
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
       - name: php-redis
         image: kubeguide/guestbook-php-frontend
         env:
         - name: GET_HOSTS_FROM
           value: env
         ports:
         - containerPort: 80
           hostPort: 8888
```
